#!/bin/csh 
#======================================================
#SBATCH -J DIAG_MEAN_RAD
#SBATCH -o diagmean_rad.o%j
#SBATCH -e diagmean_rad.err
#SBATCH -p batch
#SBATCH --mem-per-cpu=5G
#SBATCH -n 1
#SBATCH -t 0:10:00 
#======================================================

echo "BEGIN DIAG_MEAN_RAD"
date

srun --mpi=pmi2 innov_mean_radiance.exe namelist.innov.rad > diag_meanrad.output

echo "END DIAG_MEAN_RAD"

touch diagmeanrad_done

date
exit 0
